name: CI

push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    # Pull requests from the same repository won't trigger this checks as they were already triggered by the push
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Clone the code
        uses: actions/checkout@v2
      - name: Execute golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29        
          args: --timeout=5m
          only-new-issues: true # Show only new issues if it's a pull request

  validate:
    name: Validate 
    needs:
      - lint
    runs-on: ubuntu-latest
    # Pull requests from the same repository won't trigger this checks as they were already triggered by the push
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Clone the code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13'
      - name: fmt check
        run: make fmt
      - name: go mod tidy
        run: make tidy
      - name: Build
        run: make mpi-operator.v1alpha1 mpi-operator.v1alpha2 mpi-operator.v1 kubectl-delivery
      - name: Run tests
        run: make test
      - name: Send the coverage output
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage-all.out
